const initialState = {
  me: null,
  userInfo: null,
  signupLoading: false,
  signupDone: false,
  signupError: null,
  subscribeLoading: false,
  subscribeDone: false,
  subscribeError: null,
  unSubscribeLoading: false,
  unSubscribeDone: false,
  unSubscribeError: null,
  loginLoading: false,
  loginDone: false,
  loginError: null,
  logoutLoading: false,
  logoutDone: false,
  logoutError: null,
  loadMyInfoLoading: false,
  loadMyInfoDone: false,
  loadMyInfoError: null,
  loadSubscribersLoading: false,
  loadSubscribersDone: false,
  loadSubscribersError: null,
  loadProducersLoading: false,
  loadProducersDone: false,
  loadProducersError: null,
  changeNicknameLoading: false,
  changeNicknameDone: false,
  changeNicknameError: null,
};

export default initialState;